version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
    reviewers:
      - "bajtos"
      - "juliangruber"
